spring:
  application:
    name: authentificationService
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}
          jwk-set-uri: ${app.keycloak.serverUrl}/realms/${app.keycloak.realm}/protocol/openid-connect/certs


server:
  port: 8081
  servlet:
    context-path: /um


app:
  keycloak:
    admin:
      clientId: admin-cli
      clientSecret: ByUwx2jjknikEBZworyLOUvMXesMqhRS
    realm: constructionApp
    serverUrl: http://localhost:8091


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
    register-with-eureka: true



